### ISSUE TITLE
Add MQTT protocol parser 

### ISSUE THREAD

**Issue by grahamehorner** [davidfowl/Channels#136]
similar to the @davidfowl Add AMQP protocol parser, please consider adding a parser for the lightweight MQTT protocol which a common protocol for Internet of Things http://mqtt.org/

**Comment by davidfowl** [comment]
Yess!

**Comment by grahamehorner** [comment]
I would be happy to help out with regards this, and accept any guidance/ideas you may have with regards the AMQP/MQTT implementations

**Comment by Drawaes** [comment]
AMQP yes! I can chip in and help if you start, as I am interested in this for MQ Light integration

**Comment by grahamehorner** [comment]
@Drawaes happy to take some guidance from @davidfowl on how/where to hook in/up a protocol parser? @davidfowl would you suggest the constructor of parser would accept a IChannel? what would be your starting point?  If I recall doesn't Azure Service Bus support the AMQP protocol, could there be some mileage in reusing this code or basing AMQP/MQTT of it? ;)

@Drawaes https://github.com/mqtt/mqtt.github.io/wiki/servers

**Comment by Drawaes** [comment]
AMQP is an interesting one, because there are multiple "streams" in each connection (or session) I don't really know anything about MQTT and don't have the headspace for that right now but.... I would suggest that you have some sort of "wrapper" for an IChannel that you get fed by for instance a Sockets lower channel provider. Then that is your AMQP "session" off that people can request a readable link (it will be a ReadableChannel) or a writable link (WritableChannel) with some params like channel id etc off the main session. That is how I would do it, but I am by no means an expert.

**Comment by Drawaes** [comment]
@mgravell may have some insight as Http/2 is similar in that it is a single "connection" with multiple streams, but in that case I think the streams are bi-directional

**Comment by Drawaes** [comment]
@grahamehorner any more thoughts on this? I am starting to use AMQP more and more so this might jump on my priorities list shortly.
